qiniu_accessKey: 9H79eq_nap9cC8zflgmVQgEaAQzpR8zroyAyi4Uz
qiniu_secretKey: NhlQIUifNnNe7T2XkXD6t-WSeLlMB0C2J3L3mlV-
qiniu_bucket: musiclsw
#解决硬编码
upload:
  fileMap:
    qiNiuYunOSSFileUpload : mp4,avi
    minoFileUpload : jpg,png,mp3